packages: []
catalogs:
  build:
    tsdown: ^0.15.9
  cli:
    '@vscode/vsce': ^3.6.2
    bumpp: ^10.3.1
    pncat: ^0.7.3
    taze: ^19.8.1
    vsxpub: ^0.1.2
  lint:
    '@antfu/eslint-config': ^6.0.0
    eslint: ^9.38.0
    lint-staged: ^16.2.5
    simple-git-hooks: ^2.13.1
  test:
    vitest: ^3.2.4
  tsc:
    typescript: ^5.9.3
  types:
    '@types/node': ^24.9.1
  vscode:
    reactive-vscode: ^0.4.0
    vscode-ext-gen: ^1.3.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - '@vscode/vsce-sign'
  - keytar
